apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/bishal850/manifest.git'
    targetRevision: HEAD  # You can replace 'HEAD' with a specific branch/tag/commit if needed
    path: 'manifest'  # This should match the folder in your repository containing the manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

